<?php
/**
 * ShipServerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * nShift DeliveryHub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 16.134.1.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ShipServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShipServerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for shipServerActorIDAvailableServicesGet
     *
     * Get Products for actor.
     *
     */
    public function testShipServerActorIDAvailableServicesGet()
    {
    }

    /**
     * Test case for shipServerActorIDBatchReportsBatchReportIDGet
     *
     * Get batch report.
     *
     */
    public function testShipServerActorIDBatchReportsBatchReportIDGet()
    {
    }

    /**
     * Test case for shipServerActorIDBatchShipmentsBatchIDGet
     *
     * Get batch shipments.
     *
     */
    public function testShipServerActorIDBatchShipmentsBatchIDGet()
    {
    }

    /**
     * Test case for shipServerActorIDBatchesBatchIDGet
     *
     * Get Batch Details.
     *
     */
    public function testShipServerActorIDBatchesBatchIDGet()
    {
    }

    /**
     * Test case for shipServerActorIDBatchesPost
     *
     * Get Batch List.
     *
     */
    public function testShipServerActorIDBatchesPost()
    {
    }

    /**
     * Test case for shipServerActorIDCheckoutPost
     *
     * Get delivery optionswithout shipping rules defined.
     *
     */
    public function testShipServerActorIDCheckoutPost()
    {
    }

    /**
     * Test case for shipServerActorIDDropPointIDsDropPointIDPost
     *
     * Get drop point by ID.
     *
     */
    public function testShipServerActorIDDropPointIDsDropPointIDPost()
    {
    }

    /**
     * Test case for shipServerActorIDDropPointsPost
     *
     * Get drop points.
     *
     */
    public function testShipServerActorIDDropPointsPost()
    {
    }

    /**
     * Test case for shipServerActorIDImportUploadPost
     *
     * Import Upload.
     *
     */
    public function testShipServerActorIDImportUploadPost()
    {
    }

    /**
     * Test case for shipServerActorIDJobsJobIDGet
     *
     * Get job.
     *
     */
    public function testShipServerActorIDJobsJobIDGet()
    {
    }

    /**
     * Test case for shipServerActorIDOrderAdvicePost
     *
     * Creation of an order.
     *
     */
    public function testShipServerActorIDOrderAdvicePost()
    {
    }

    /**
     * Test case for shipServerActorIDOrdersPost
     *
     * Store order.
     *
     */
    public function testShipServerActorIDOrdersPost()
    {
    }

    /**
     * Test case for shipServerActorIDPackagesManifestPut
     *
     * Transmit/manifest packages.
     *
     */
    public function testShipServerActorIDPackagesManifestPut()
    {
    }

    /**
     * Test case for shipServerActorIDPickupLockerAllocationsPost
     *
     * Pickup Locker Allocations.
     *
     */
    public function testShipServerActorIDPickupLockerAllocationsPost()
    {
    }

    /**
     * Test case for shipServerActorIDPickupLockersPost
     *
     * Get pickup lockers.
     *
     */
    public function testShipServerActorIDPickupLockersPost()
    {
    }

    /**
     * Test case for shipServerActorIDProductsGet
     *
     * Get Products.
     *
     */
    public function testShipServerActorIDProductsGet()
    {
    }

    /**
     * Test case for shipServerActorIDSaveShipmentPost
     *
     * Save shipment.
     *
     */
    public function testShipServerActorIDSaveShipmentPost()
    {
    }

    /**
     * Test case for shipServerActorIDSenderAddressGet
     *
     * Get Sender Address.
     *
     */
    public function testShipServerActorIDSenderAddressGet()
    {
    }

    /**
     * Test case for shipServerActorIDShipAdvisesPost
     *
     * Get delivery options.
     *
     */
    public function testShipServerActorIDShipAdvisesPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentPricesPost
     *
     * Get Shipment Price.
     *
     */
    public function testShipServerActorIDShipmentPricesPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentValidationsPost
     *
     * Validate shipment.
     *
     */
    public function testShipServerActorIDShipmentValidationsPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsDefaultsPost
     *
     * Apply defaults on shipment.
     *
     */
    public function testShipServerActorIDShipmentsDefaultsPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsLabelReprintPost
     *
     * Reprint Labels.
     *
     */
    public function testShipServerActorIDShipmentsLabelReprintPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsManifestPut
     *
     * Transmit/manifest Shipments.
     *
     */
    public function testShipServerActorIDShipmentsManifestPut()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsPost
     *
     * Submit/Print Shipment.
     *
     */
    public function testShipServerActorIDShipmentsPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagDelete
     *
     * Delete shipment.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagDelete()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagDetailsPatch
     *
     * Update Details.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagDetailsPatch()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagDocumentListsGet
     *
     * Get document list for a shipment.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagDocumentListsGet()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagDocumentsGet
     *
     * Get documents for a shipment.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagDocumentsGet()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagGet
     *
     * Get existing shipment.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagGet()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagLinesLineTagDelete
     *
     * Delete line.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagLinesLineTagDelete()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagLinesLineTagPatch
     *
     * Update Line.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagLinesLineTagPatch()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagLinesPost
     *
     * New shipment line.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagLinesPost()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagPackagesPackageTagDelete
     *
     * Delete package.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagPackagesPackageTagDelete()
    {
    }

    /**
     * Test case for shipServerActorIDShipmentsShipmentTagTrackingURLGet
     *
     * Get Tracking URL.
     *
     */
    public function testShipServerActorIDShipmentsShipmentTagTrackingURLGet()
    {
    }

    /**
     * Test case for shipServerActorIDShippingRulesPost
     *
     * Save shipping rules.
     *
     */
    public function testShipServerActorIDShippingRulesPost()
    {
    }

    /**
     * Test case for shipServerActorIDStacksGet
     *
     * Get stacks.
     *
     */
    public function testShipServerActorIDStacksGet()
    {
    }

    /**
     * Test case for shipServerActorIDStacksPost
     *
     * Create stack.
     *
     */
    public function testShipServerActorIDStacksPost()
    {
    }

    /**
     * Test case for shipServerActorIDStacksShipmentsPatch
     *
     * Move shipments.
     *
     */
    public function testShipServerActorIDStacksShipmentsPatch()
    {
    }

    /**
     * Test case for shipServerActorIDStacksShipmentsPost
     *
     * Get stackshipments.
     *
     */
    public function testShipServerActorIDStacksShipmentsPost()
    {
    }

    /**
     * Test case for shipServerActorIDStacksStackIDDelete
     *
     * Delete stack.
     *
     */
    public function testShipServerActorIDStacksStackIDDelete()
    {
    }

    /**
     * Test case for shipServerActorIDStacksStackIDManifestPut
     *
     * Transmit stack.
     *
     */
    public function testShipServerActorIDStacksStackIDManifestPut()
    {
    }

    /**
     * Test case for shipServerActorIDSubmitOrderPost
     *
     * Submit order.
     *
     */
    public function testShipServerActorIDSubmitOrderPost()
    {
    }

    /**
     * Test case for shipServerActorIDTimeSlotAllocationsPost
     *
     * Time slot allocations.
     *
     */
    public function testShipServerActorIDTimeSlotAllocationsPost()
    {
    }

    /**
     * Test case for shipServerActorIDTimeSlotsPost
     *
     * Get time slots.
     *
     */
    public function testShipServerActorIDTimeSlotsPost()
    {
    }

    /**
     * Test case for shipServerActorIDValidRoutesPost
     *
     * Check sender/receiver addresses..
     *
     */
    public function testShipServerActorIDValidRoutesPost()
    {
    }

    /**
     * Test case for shipServerActorIDVoidTimeSlotPost
     *
     * Void Time slot.
     *
     */
    public function testShipServerActorIDVoidTimeSlotPost()
    {
    }

    /**
     * Test case for shipServerActorIDWaybillsPost
     *
     * Get waybills.
     *
     */
    public function testShipServerActorIDWaybillsPost()
    {
    }
}
